// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClipData.proto

#include "ClipData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ClipData_proto::ClipData_proto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.poframebucketentry_)*/{}
  , /*decltype(_impl_.numkeyframes_)*/0u
  , /*decltype(_impl_.numbones_)*/0u} {}
struct ClipData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClipData_protoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClipData_protoDefaultTypeInternal() {}
  union {
    ClipData_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClipData_protoDefaultTypeInternal _ClipData_proto_default_instance_;

// ===================================================================

class ClipData_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<ClipData_proto>()._impl_._has_bits_);
  static void set_has_numkeyframes(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_numbones(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

void ClipData_proto::clear_poframebucketentry() {
  _impl_.poframebucketentry_.Clear();
}
ClipData_proto::ClipData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ClipData_proto)
}
ClipData_proto::ClipData_proto(const ClipData_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ClipData_proto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.poframebucketentry_){from._impl_.poframebucketentry_}
    , decltype(_impl_.numkeyframes_){}
    , decltype(_impl_.numbones_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&_impl_.numkeyframes_, &from._impl_.numkeyframes_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.numbones_) -
    reinterpret_cast<char*>(&_impl_.numkeyframes_)) + sizeof(_impl_.numbones_));
  // @@protoc_insertion_point(copy_constructor:ClipData_proto)
}

inline void ClipData_proto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.poframebucketentry_){arena}
    , decltype(_impl_.numkeyframes_){0u}
    , decltype(_impl_.numbones_){0u}
  };
}

ClipData_proto::~ClipData_proto() {
  // @@protoc_insertion_point(destructor:ClipData_proto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClipData_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.poframebucketentry_.~RepeatedPtrField();
}

void ClipData_proto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClipData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:ClipData_proto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.poframebucketentry_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.numkeyframes_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.numbones_) -
        reinterpret_cast<char*>(&_impl_.numkeyframes_)) + sizeof(_impl_.numbones_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* ClipData_proto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 numKeyFrames = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_numkeyframes(&has_bits);
          _impl_.numkeyframes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 numBones = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_numbones(&has_bits);
          _impl_.numbones_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .FrameBucketEntry_proto poFrameBucketEntry = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_poframebucketentry(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClipData_proto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClipData_proto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 numKeyFrames = 1;
  if (_internal_has_numkeyframes()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_numkeyframes(), target);
  }

  // optional uint32 numBones = 2;
  if (_internal_has_numbones()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_numbones(), target);
  }

  // repeated .FrameBucketEntry_proto poFrameBucketEntry = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_poframebucketentry_size()); i < n; i++) {
    const auto& repfield = this->_internal_poframebucketentry(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClipData_proto)
  return target;
}

size_t ClipData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClipData_proto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .FrameBucketEntry_proto poFrameBucketEntry = 3;
  total_size += 1UL * this->_internal_poframebucketentry_size();
  for (const auto& msg : this->_impl_.poframebucketentry_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional uint32 numKeyFrames = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_numkeyframes());
    }

    // optional uint32 numBones = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_numbones());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClipData_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ClipData_proto*>(
      &from));
}

void ClipData_proto::MergeFrom(const ClipData_proto& from) {
  ClipData_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:ClipData_proto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.poframebucketentry_.MergeFrom(from._impl_.poframebucketentry_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.numkeyframes_ = from._impl_.numkeyframes_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.numbones_ = from._impl_.numbones_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ClipData_proto::CopyFrom(const ClipData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClipData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClipData_proto::IsInitialized() const {
  return true;
}

void ClipData_proto::InternalSwap(ClipData_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.poframebucketentry_.InternalSwap(&other->_impl_.poframebucketentry_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClipData_proto, _impl_.numbones_)
      + sizeof(ClipData_proto::_impl_.numbones_)
      - PROTOBUF_FIELD_OFFSET(ClipData_proto, _impl_.numkeyframes_)>(
          reinterpret_cast<char*>(&_impl_.numkeyframes_),
          reinterpret_cast<char*>(&other->_impl_.numkeyframes_));
}

std::string ClipData_proto::GetTypeName() const {
  return "ClipData_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ClipData_proto*
Arena::CreateMaybeMessage< ::ClipData_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ClipData_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
