// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClipData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ClipData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ClipData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "FrameBucketEntry.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ClipData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ClipData_2eproto {
  static const uint32_t offsets[];
};
class ClipData_proto;
struct ClipData_protoDefaultTypeInternal;
extern ClipData_protoDefaultTypeInternal _ClipData_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ClipData_proto* Arena::CreateMaybeMessage<::ClipData_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ClipData_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:ClipData_proto) */ {
 public:
  inline ClipData_proto() : ClipData_proto(nullptr) {}
  ~ClipData_proto() override;
  explicit PROTOBUF_CONSTEXPR ClipData_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClipData_proto(const ClipData_proto& from);
  ClipData_proto(ClipData_proto&& from) noexcept
    : ClipData_proto() {
    *this = ::std::move(from);
  }

  inline ClipData_proto& operator=(const ClipData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClipData_proto& operator=(ClipData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ClipData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClipData_proto* internal_default_instance() {
    return reinterpret_cast<const ClipData_proto*>(
               &_ClipData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClipData_proto& a, ClipData_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(ClipData_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClipData_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClipData_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClipData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ClipData_proto& from);
  void MergeFrom(const ClipData_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClipData_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClipData_proto";
  }
  protected:
  explicit ClipData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoFrameBucketEntryFieldNumber = 3,
    kNumKeyFramesFieldNumber = 1,
    kNumBonesFieldNumber = 2,
  };
  // repeated .FrameBucketEntry_proto poFrameBucketEntry = 3;
  int poframebucketentry_size() const;
  private:
  int _internal_poframebucketentry_size() const;
  public:
  void clear_poframebucketentry();
  ::FrameBucketEntry_proto* mutable_poframebucketentry(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FrameBucketEntry_proto >*
      mutable_poframebucketentry();
  private:
  const ::FrameBucketEntry_proto& _internal_poframebucketentry(int index) const;
  ::FrameBucketEntry_proto* _internal_add_poframebucketentry();
  public:
  const ::FrameBucketEntry_proto& poframebucketentry(int index) const;
  ::FrameBucketEntry_proto* add_poframebucketentry();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FrameBucketEntry_proto >&
      poframebucketentry() const;

  // optional uint32 numKeyFrames = 1;
  bool has_numkeyframes() const;
  private:
  bool _internal_has_numkeyframes() const;
  public:
  void clear_numkeyframes();
  uint32_t numkeyframes() const;
  void set_numkeyframes(uint32_t value);
  private:
  uint32_t _internal_numkeyframes() const;
  void _internal_set_numkeyframes(uint32_t value);
  public:

  // optional uint32 numBones = 2;
  bool has_numbones() const;
  private:
  bool _internal_has_numbones() const;
  public:
  void clear_numbones();
  uint32_t numbones() const;
  void set_numbones(uint32_t value);
  private:
  uint32_t _internal_numbones() const;
  void _internal_set_numbones(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ClipData_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FrameBucketEntry_proto > poframebucketentry_;
    uint32_t numkeyframes_;
    uint32_t numbones_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClipData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClipData_proto

// optional uint32 numKeyFrames = 1;
inline bool ClipData_proto::_internal_has_numkeyframes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ClipData_proto::has_numkeyframes() const {
  return _internal_has_numkeyframes();
}
inline void ClipData_proto::clear_numkeyframes() {
  _impl_.numkeyframes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t ClipData_proto::_internal_numkeyframes() const {
  return _impl_.numkeyframes_;
}
inline uint32_t ClipData_proto::numkeyframes() const {
  // @@protoc_insertion_point(field_get:ClipData_proto.numKeyFrames)
  return _internal_numkeyframes();
}
inline void ClipData_proto::_internal_set_numkeyframes(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.numkeyframes_ = value;
}
inline void ClipData_proto::set_numkeyframes(uint32_t value) {
  _internal_set_numkeyframes(value);
  // @@protoc_insertion_point(field_set:ClipData_proto.numKeyFrames)
}

// optional uint32 numBones = 2;
inline bool ClipData_proto::_internal_has_numbones() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ClipData_proto::has_numbones() const {
  return _internal_has_numbones();
}
inline void ClipData_proto::clear_numbones() {
  _impl_.numbones_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t ClipData_proto::_internal_numbones() const {
  return _impl_.numbones_;
}
inline uint32_t ClipData_proto::numbones() const {
  // @@protoc_insertion_point(field_get:ClipData_proto.numBones)
  return _internal_numbones();
}
inline void ClipData_proto::_internal_set_numbones(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.numbones_ = value;
}
inline void ClipData_proto::set_numbones(uint32_t value) {
  _internal_set_numbones(value);
  // @@protoc_insertion_point(field_set:ClipData_proto.numBones)
}

// repeated .FrameBucketEntry_proto poFrameBucketEntry = 3;
inline int ClipData_proto::_internal_poframebucketentry_size() const {
  return _impl_.poframebucketentry_.size();
}
inline int ClipData_proto::poframebucketentry_size() const {
  return _internal_poframebucketentry_size();
}
inline ::FrameBucketEntry_proto* ClipData_proto::mutable_poframebucketentry(int index) {
  // @@protoc_insertion_point(field_mutable:ClipData_proto.poFrameBucketEntry)
  return _impl_.poframebucketentry_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FrameBucketEntry_proto >*
ClipData_proto::mutable_poframebucketentry() {
  // @@protoc_insertion_point(field_mutable_list:ClipData_proto.poFrameBucketEntry)
  return &_impl_.poframebucketentry_;
}
inline const ::FrameBucketEntry_proto& ClipData_proto::_internal_poframebucketentry(int index) const {
  return _impl_.poframebucketentry_.Get(index);
}
inline const ::FrameBucketEntry_proto& ClipData_proto::poframebucketentry(int index) const {
  // @@protoc_insertion_point(field_get:ClipData_proto.poFrameBucketEntry)
  return _internal_poframebucketentry(index);
}
inline ::FrameBucketEntry_proto* ClipData_proto::_internal_add_poframebucketentry() {
  return _impl_.poframebucketentry_.Add();
}
inline ::FrameBucketEntry_proto* ClipData_proto::add_poframebucketentry() {
  ::FrameBucketEntry_proto* _add = _internal_add_poframebucketentry();
  // @@protoc_insertion_point(field_add:ClipData_proto.poFrameBucketEntry)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FrameBucketEntry_proto >&
ClipData_proto::poframebucketentry() const {
  // @@protoc_insertion_point(field_list:ClipData_proto.poFrameBucketEntry)
  return _impl_.poframebucketentry_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ClipData_2eproto
