// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FontData.proto

#include "FontData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR FontData_proto::FontData_proto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.pofontentry_)*/{}
  , /*decltype(_impl_.numkeys_)*/0u} {}
struct FontData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FontData_protoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FontData_protoDefaultTypeInternal() {}
  union {
    FontData_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FontData_protoDefaultTypeInternal _FontData_proto_default_instance_;

// ===================================================================

class FontData_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<FontData_proto>()._impl_._has_bits_);
  static void set_has_numkeys(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

void FontData_proto::clear_pofontentry() {
  _impl_.pofontentry_.Clear();
}
FontData_proto::FontData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:FontData_proto)
}
FontData_proto::FontData_proto(const FontData_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  FontData_proto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pofontentry_){from._impl_.pofontentry_}
    , decltype(_impl_.numkeys_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _this->_impl_.numkeys_ = from._impl_.numkeys_;
  // @@protoc_insertion_point(copy_constructor:FontData_proto)
}

inline void FontData_proto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pofontentry_){arena}
    , decltype(_impl_.numkeys_){0u}
  };
}

FontData_proto::~FontData_proto() {
  // @@protoc_insertion_point(destructor:FontData_proto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FontData_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pofontentry_.~RepeatedPtrField();
}

void FontData_proto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FontData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:FontData_proto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pofontentry_.Clear();
  _impl_.numkeys_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* FontData_proto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 numKeys = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_numkeys(&has_bits);
          _impl_.numkeys_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .FontEntry_proto poFontEntry = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_pofontentry(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FontData_proto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FontData_proto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 numKeys = 1;
  if (_internal_has_numkeys()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_numkeys(), target);
  }

  // repeated .FontEntry_proto poFontEntry = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_pofontentry_size()); i < n; i++) {
    const auto& repfield = this->_internal_pofontentry(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FontData_proto)
  return target;
}

size_t FontData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FontData_proto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .FontEntry_proto poFontEntry = 2;
  total_size += 1UL * this->_internal_pofontentry_size();
  for (const auto& msg : this->_impl_.pofontentry_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional uint32 numKeys = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_numkeys());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FontData_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const FontData_proto*>(
      &from));
}

void FontData_proto::MergeFrom(const FontData_proto& from) {
  FontData_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:FontData_proto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.pofontentry_.MergeFrom(from._impl_.pofontentry_);
  if (from._internal_has_numkeys()) {
    _this->_internal_set_numkeys(from._internal_numkeys());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void FontData_proto::CopyFrom(const FontData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FontData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FontData_proto::IsInitialized() const {
  return true;
}

void FontData_proto::InternalSwap(FontData_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pofontentry_.InternalSwap(&other->_impl_.pofontentry_);
  swap(_impl_.numkeys_, other->_impl_.numkeys_);
}

std::string FontData_proto::GetTypeName() const {
  return "FontData_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::FontData_proto*
Arena::CreateMaybeMessage< ::FontData_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::FontData_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
