// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FontEntry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_FontEntry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_FontEntry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_FontEntry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_FontEntry_2eproto {
  static const uint32_t offsets[];
};
class FontEntry_proto;
struct FontEntry_protoDefaultTypeInternal;
extern FontEntry_protoDefaultTypeInternal _FontEntry_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::FontEntry_proto* Arena::CreateMaybeMessage<::FontEntry_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class FontEntry_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:FontEntry_proto) */ {
 public:
  inline FontEntry_proto() : FontEntry_proto(nullptr) {}
  ~FontEntry_proto() override;
  explicit PROTOBUF_CONSTEXPR FontEntry_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FontEntry_proto(const FontEntry_proto& from);
  FontEntry_proto(FontEntry_proto&& from) noexcept
    : FontEntry_proto() {
    *this = ::std::move(from);
  }

  inline FontEntry_proto& operator=(const FontEntry_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline FontEntry_proto& operator=(FontEntry_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const FontEntry_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const FontEntry_proto* internal_default_instance() {
    return reinterpret_cast<const FontEntry_proto*>(
               &_FontEntry_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FontEntry_proto& a, FontEntry_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(FontEntry_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FontEntry_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FontEntry_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FontEntry_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const FontEntry_proto& from);
  void MergeFrom(const FontEntry_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FontEntry_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "FontEntry_proto";
  }
  protected:
  explicit FontEntry_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kWidthFieldNumber = 4,
    kHeightFieldNumber = 5,
  };
  // optional uint32 key = 1;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  uint32_t key() const;
  void set_key(uint32_t value);
  private:
  uint32_t _internal_key() const;
  void _internal_set_key(uint32_t value);
  public:

  // optional float x = 2;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // optional float y = 3;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // optional float width = 4;
  bool has_width() const;
  private:
  bool _internal_has_width() const;
  public:
  void clear_width();
  float width() const;
  void set_width(float value);
  private:
  float _internal_width() const;
  void _internal_set_width(float value);
  public:

  // optional float height = 5;
  bool has_height() const;
  private:
  bool _internal_has_height() const;
  public:
  void clear_height();
  float height() const;
  void set_height(float value);
  private:
  float _internal_height() const;
  void _internal_set_height(float value);
  public:

  // @@protoc_insertion_point(class_scope:FontEntry_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t key_;
    float x_;
    float y_;
    float width_;
    float height_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FontEntry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FontEntry_proto

// optional uint32 key = 1;
inline bool FontEntry_proto::_internal_has_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FontEntry_proto::has_key() const {
  return _internal_has_key();
}
inline void FontEntry_proto::clear_key() {
  _impl_.key_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t FontEntry_proto::_internal_key() const {
  return _impl_.key_;
}
inline uint32_t FontEntry_proto::key() const {
  // @@protoc_insertion_point(field_get:FontEntry_proto.key)
  return _internal_key();
}
inline void FontEntry_proto::_internal_set_key(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.key_ = value;
}
inline void FontEntry_proto::set_key(uint32_t value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:FontEntry_proto.key)
}

// optional float x = 2;
inline bool FontEntry_proto::_internal_has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool FontEntry_proto::has_x() const {
  return _internal_has_x();
}
inline void FontEntry_proto::clear_x() {
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float FontEntry_proto::_internal_x() const {
  return _impl_.x_;
}
inline float FontEntry_proto::x() const {
  // @@protoc_insertion_point(field_get:FontEntry_proto.x)
  return _internal_x();
}
inline void FontEntry_proto::_internal_set_x(float value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.x_ = value;
}
inline void FontEntry_proto::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:FontEntry_proto.x)
}

// optional float y = 3;
inline bool FontEntry_proto::_internal_has_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool FontEntry_proto::has_y() const {
  return _internal_has_y();
}
inline void FontEntry_proto::clear_y() {
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float FontEntry_proto::_internal_y() const {
  return _impl_.y_;
}
inline float FontEntry_proto::y() const {
  // @@protoc_insertion_point(field_get:FontEntry_proto.y)
  return _internal_y();
}
inline void FontEntry_proto::_internal_set_y(float value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.y_ = value;
}
inline void FontEntry_proto::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:FontEntry_proto.y)
}

// optional float width = 4;
inline bool FontEntry_proto::_internal_has_width() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool FontEntry_proto::has_width() const {
  return _internal_has_width();
}
inline void FontEntry_proto::clear_width() {
  _impl_.width_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float FontEntry_proto::_internal_width() const {
  return _impl_.width_;
}
inline float FontEntry_proto::width() const {
  // @@protoc_insertion_point(field_get:FontEntry_proto.width)
  return _internal_width();
}
inline void FontEntry_proto::_internal_set_width(float value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.width_ = value;
}
inline void FontEntry_proto::set_width(float value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:FontEntry_proto.width)
}

// optional float height = 5;
inline bool FontEntry_proto::_internal_has_height() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool FontEntry_proto::has_height() const {
  return _internal_has_height();
}
inline void FontEntry_proto::clear_height() {
  _impl_.height_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline float FontEntry_proto::_internal_height() const {
  return _impl_.height_;
}
inline float FontEntry_proto::height() const {
  // @@protoc_insertion_point(field_get:FontEntry_proto.height)
  return _internal_height();
}
inline void FontEntry_proto::_internal_set_height(float value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.height_ = value;
}
inline void FontEntry_proto::set_height(float value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:FontEntry_proto.height)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_FontEntry_2eproto
