// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FrameBucketEntry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_FrameBucketEntry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_FrameBucketEntry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "BoneEntry.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_FrameBucketEntry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_FrameBucketEntry_2eproto {
  static const uint32_t offsets[];
};
class FrameBucketEntry_proto;
struct FrameBucketEntry_protoDefaultTypeInternal;
extern FrameBucketEntry_protoDefaultTypeInternal _FrameBucketEntry_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::FrameBucketEntry_proto* Arena::CreateMaybeMessage<::FrameBucketEntry_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class FrameBucketEntry_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:FrameBucketEntry_proto) */ {
 public:
  inline FrameBucketEntry_proto() : FrameBucketEntry_proto(nullptr) {}
  ~FrameBucketEntry_proto() override;
  explicit PROTOBUF_CONSTEXPR FrameBucketEntry_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameBucketEntry_proto(const FrameBucketEntry_proto& from);
  FrameBucketEntry_proto(FrameBucketEntry_proto&& from) noexcept
    : FrameBucketEntry_proto() {
    *this = ::std::move(from);
  }

  inline FrameBucketEntry_proto& operator=(const FrameBucketEntry_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameBucketEntry_proto& operator=(FrameBucketEntry_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const FrameBucketEntry_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameBucketEntry_proto* internal_default_instance() {
    return reinterpret_cast<const FrameBucketEntry_proto*>(
               &_FrameBucketEntry_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameBucketEntry_proto& a, FrameBucketEntry_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameBucketEntry_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameBucketEntry_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameBucketEntry_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameBucketEntry_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const FrameBucketEntry_proto& from);
  void MergeFrom(const FrameBucketEntry_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FrameBucketEntry_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "FrameBucketEntry_proto";
  }
  protected:
  explicit FrameBucketEntry_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoBoneEntryFieldNumber = 5,
    kKeyFrameFieldNumber = 1,
    kNumBonesFieldNumber = 2,
    kKeyTimeFieldNumber = 3,
    kKeyTimeIndexFieldNumber = 4,
  };
  // repeated .BoneEntry_proto poBoneEntry = 5;
  int poboneentry_size() const;
  private:
  int _internal_poboneentry_size() const;
  public:
  void clear_poboneentry();
  ::BoneEntry_proto* mutable_poboneentry(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::BoneEntry_proto >*
      mutable_poboneentry();
  private:
  const ::BoneEntry_proto& _internal_poboneentry(int index) const;
  ::BoneEntry_proto* _internal_add_poboneentry();
  public:
  const ::BoneEntry_proto& poboneentry(int index) const;
  ::BoneEntry_proto* add_poboneentry();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::BoneEntry_proto >&
      poboneentry() const;

  // optional uint32 keyFrame = 1;
  bool has_keyframe() const;
  private:
  bool _internal_has_keyframe() const;
  public:
  void clear_keyframe();
  uint32_t keyframe() const;
  void set_keyframe(uint32_t value);
  private:
  uint32_t _internal_keyframe() const;
  void _internal_set_keyframe(uint32_t value);
  public:

  // optional uint32 numBones = 2;
  bool has_numbones() const;
  private:
  bool _internal_has_numbones() const;
  public:
  void clear_numbones();
  uint32_t numbones() const;
  void set_numbones(uint32_t value);
  private:
  uint32_t _internal_numbones() const;
  void _internal_set_numbones(uint32_t value);
  public:

  // optional float keyTime = 3;
  bool has_keytime() const;
  private:
  bool _internal_has_keytime() const;
  public:
  void clear_keytime();
  float keytime() const;
  void set_keytime(float value);
  private:
  float _internal_keytime() const;
  void _internal_set_keytime(float value);
  public:

  // optional int32 keyTimeIndex = 4;
  bool has_keytimeindex() const;
  private:
  bool _internal_has_keytimeindex() const;
  public:
  void clear_keytimeindex();
  int32_t keytimeindex() const;
  void set_keytimeindex(int32_t value);
  private:
  int32_t _internal_keytimeindex() const;
  void _internal_set_keytimeindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:FrameBucketEntry_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::BoneEntry_proto > poboneentry_;
    uint32_t keyframe_;
    uint32_t numbones_;
    float keytime_;
    int32_t keytimeindex_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FrameBucketEntry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameBucketEntry_proto

// optional uint32 keyFrame = 1;
inline bool FrameBucketEntry_proto::_internal_has_keyframe() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FrameBucketEntry_proto::has_keyframe() const {
  return _internal_has_keyframe();
}
inline void FrameBucketEntry_proto::clear_keyframe() {
  _impl_.keyframe_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t FrameBucketEntry_proto::_internal_keyframe() const {
  return _impl_.keyframe_;
}
inline uint32_t FrameBucketEntry_proto::keyframe() const {
  // @@protoc_insertion_point(field_get:FrameBucketEntry_proto.keyFrame)
  return _internal_keyframe();
}
inline void FrameBucketEntry_proto::_internal_set_keyframe(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.keyframe_ = value;
}
inline void FrameBucketEntry_proto::set_keyframe(uint32_t value) {
  _internal_set_keyframe(value);
  // @@protoc_insertion_point(field_set:FrameBucketEntry_proto.keyFrame)
}

// optional uint32 numBones = 2;
inline bool FrameBucketEntry_proto::_internal_has_numbones() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool FrameBucketEntry_proto::has_numbones() const {
  return _internal_has_numbones();
}
inline void FrameBucketEntry_proto::clear_numbones() {
  _impl_.numbones_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t FrameBucketEntry_proto::_internal_numbones() const {
  return _impl_.numbones_;
}
inline uint32_t FrameBucketEntry_proto::numbones() const {
  // @@protoc_insertion_point(field_get:FrameBucketEntry_proto.numBones)
  return _internal_numbones();
}
inline void FrameBucketEntry_proto::_internal_set_numbones(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.numbones_ = value;
}
inline void FrameBucketEntry_proto::set_numbones(uint32_t value) {
  _internal_set_numbones(value);
  // @@protoc_insertion_point(field_set:FrameBucketEntry_proto.numBones)
}

// optional float keyTime = 3;
inline bool FrameBucketEntry_proto::_internal_has_keytime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool FrameBucketEntry_proto::has_keytime() const {
  return _internal_has_keytime();
}
inline void FrameBucketEntry_proto::clear_keytime() {
  _impl_.keytime_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float FrameBucketEntry_proto::_internal_keytime() const {
  return _impl_.keytime_;
}
inline float FrameBucketEntry_proto::keytime() const {
  // @@protoc_insertion_point(field_get:FrameBucketEntry_proto.keyTime)
  return _internal_keytime();
}
inline void FrameBucketEntry_proto::_internal_set_keytime(float value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.keytime_ = value;
}
inline void FrameBucketEntry_proto::set_keytime(float value) {
  _internal_set_keytime(value);
  // @@protoc_insertion_point(field_set:FrameBucketEntry_proto.keyTime)
}

// optional int32 keyTimeIndex = 4;
inline bool FrameBucketEntry_proto::_internal_has_keytimeindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool FrameBucketEntry_proto::has_keytimeindex() const {
  return _internal_has_keytimeindex();
}
inline void FrameBucketEntry_proto::clear_keytimeindex() {
  _impl_.keytimeindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline int32_t FrameBucketEntry_proto::_internal_keytimeindex() const {
  return _impl_.keytimeindex_;
}
inline int32_t FrameBucketEntry_proto::keytimeindex() const {
  // @@protoc_insertion_point(field_get:FrameBucketEntry_proto.keyTimeIndex)
  return _internal_keytimeindex();
}
inline void FrameBucketEntry_proto::_internal_set_keytimeindex(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.keytimeindex_ = value;
}
inline void FrameBucketEntry_proto::set_keytimeindex(int32_t value) {
  _internal_set_keytimeindex(value);
  // @@protoc_insertion_point(field_set:FrameBucketEntry_proto.keyTimeIndex)
}

// repeated .BoneEntry_proto poBoneEntry = 5;
inline int FrameBucketEntry_proto::_internal_poboneentry_size() const {
  return _impl_.poboneentry_.size();
}
inline int FrameBucketEntry_proto::poboneentry_size() const {
  return _internal_poboneentry_size();
}
inline ::BoneEntry_proto* FrameBucketEntry_proto::mutable_poboneentry(int index) {
  // @@protoc_insertion_point(field_mutable:FrameBucketEntry_proto.poBoneEntry)
  return _impl_.poboneentry_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::BoneEntry_proto >*
FrameBucketEntry_proto::mutable_poboneentry() {
  // @@protoc_insertion_point(field_mutable_list:FrameBucketEntry_proto.poBoneEntry)
  return &_impl_.poboneentry_;
}
inline const ::BoneEntry_proto& FrameBucketEntry_proto::_internal_poboneentry(int index) const {
  return _impl_.poboneentry_.Get(index);
}
inline const ::BoneEntry_proto& FrameBucketEntry_proto::poboneentry(int index) const {
  // @@protoc_insertion_point(field_get:FrameBucketEntry_proto.poBoneEntry)
  return _internal_poboneentry(index);
}
inline ::BoneEntry_proto* FrameBucketEntry_proto::_internal_add_poboneentry() {
  return _impl_.poboneentry_.Add();
}
inline ::BoneEntry_proto* FrameBucketEntry_proto::add_poboneentry() {
  ::BoneEntry_proto* _add = _internal_add_poboneentry();
  // @@protoc_insertion_point(field_add:FrameBucketEntry_proto.poBoneEntry)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::BoneEntry_proto >&
FrameBucketEntry_proto::poboneentry() const {
  // @@protoc_insertion_point(field_list:FrameBucketEntry_proto.poBoneEntry)
  return _impl_.poboneentry_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_FrameBucketEntry_2eproto
