// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FrameBucketEntry.proto

#include "FrameBucketEntry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR FrameBucketEntry_proto::FrameBucketEntry_proto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.poboneentry_)*/{}
  , /*decltype(_impl_.keyframe_)*/0u
  , /*decltype(_impl_.numbones_)*/0u
  , /*decltype(_impl_.keytime_)*/0
  , /*decltype(_impl_.keytimeindex_)*/0} {}
struct FrameBucketEntry_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameBucketEntry_protoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameBucketEntry_protoDefaultTypeInternal() {}
  union {
    FrameBucketEntry_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameBucketEntry_protoDefaultTypeInternal _FrameBucketEntry_proto_default_instance_;

// ===================================================================

class FrameBucketEntry_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<FrameBucketEntry_proto>()._impl_._has_bits_);
  static void set_has_keyframe(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_numbones(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_keytime(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_keytimeindex(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

void FrameBucketEntry_proto::clear_poboneentry() {
  _impl_.poboneentry_.Clear();
}
FrameBucketEntry_proto::FrameBucketEntry_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:FrameBucketEntry_proto)
}
FrameBucketEntry_proto::FrameBucketEntry_proto(const FrameBucketEntry_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  FrameBucketEntry_proto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.poboneentry_){from._impl_.poboneentry_}
    , decltype(_impl_.keyframe_){}
    , decltype(_impl_.numbones_){}
    , decltype(_impl_.keytime_){}
    , decltype(_impl_.keytimeindex_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&_impl_.keyframe_, &from._impl_.keyframe_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.keytimeindex_) -
    reinterpret_cast<char*>(&_impl_.keyframe_)) + sizeof(_impl_.keytimeindex_));
  // @@protoc_insertion_point(copy_constructor:FrameBucketEntry_proto)
}

inline void FrameBucketEntry_proto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.poboneentry_){arena}
    , decltype(_impl_.keyframe_){0u}
    , decltype(_impl_.numbones_){0u}
    , decltype(_impl_.keytime_){0}
    , decltype(_impl_.keytimeindex_){0}
  };
}

FrameBucketEntry_proto::~FrameBucketEntry_proto() {
  // @@protoc_insertion_point(destructor:FrameBucketEntry_proto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FrameBucketEntry_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.poboneentry_.~RepeatedPtrField();
}

void FrameBucketEntry_proto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FrameBucketEntry_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:FrameBucketEntry_proto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.poboneentry_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.keyframe_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.keytimeindex_) -
        reinterpret_cast<char*>(&_impl_.keyframe_)) + sizeof(_impl_.keytimeindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* FrameBucketEntry_proto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 keyFrame = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_keyframe(&has_bits);
          _impl_.keyframe_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 numBones = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_numbones(&has_bits);
          _impl_.numbones_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional float keyTime = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _Internal::set_has_keytime(&has_bits);
          _impl_.keytime_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional int32 keyTimeIndex = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_keytimeindex(&has_bits);
          _impl_.keytimeindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .BoneEntry_proto poBoneEntry = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_poboneentry(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FrameBucketEntry_proto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FrameBucketEntry_proto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 keyFrame = 1;
  if (_internal_has_keyframe()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_keyframe(), target);
  }

  // optional uint32 numBones = 2;
  if (_internal_has_numbones()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_numbones(), target);
  }

  // optional float keyTime = 3;
  if (_internal_has_keytime()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_keytime(), target);
  }

  // optional int32 keyTimeIndex = 4;
  if (_internal_has_keytimeindex()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_keytimeindex(), target);
  }

  // repeated .BoneEntry_proto poBoneEntry = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_poboneentry_size()); i < n; i++) {
    const auto& repfield = this->_internal_poboneentry(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FrameBucketEntry_proto)
  return target;
}

size_t FrameBucketEntry_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FrameBucketEntry_proto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BoneEntry_proto poBoneEntry = 5;
  total_size += 1UL * this->_internal_poboneentry_size();
  for (const auto& msg : this->_impl_.poboneentry_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional uint32 keyFrame = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_keyframe());
    }

    // optional uint32 numBones = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_numbones());
    }

    // optional float keyTime = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 4;
    }

    // optional int32 keyTimeIndex = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_keytimeindex());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FrameBucketEntry_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const FrameBucketEntry_proto*>(
      &from));
}

void FrameBucketEntry_proto::MergeFrom(const FrameBucketEntry_proto& from) {
  FrameBucketEntry_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:FrameBucketEntry_proto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.poboneentry_.MergeFrom(from._impl_.poboneentry_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.keyframe_ = from._impl_.keyframe_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.numbones_ = from._impl_.numbones_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.keytime_ = from._impl_.keytime_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.keytimeindex_ = from._impl_.keytimeindex_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void FrameBucketEntry_proto::CopyFrom(const FrameBucketEntry_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FrameBucketEntry_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FrameBucketEntry_proto::IsInitialized() const {
  return true;
}

void FrameBucketEntry_proto::InternalSwap(FrameBucketEntry_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.poboneentry_.InternalSwap(&other->_impl_.poboneentry_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keytimeindex_)
      + sizeof(FrameBucketEntry_proto::_impl_.keytimeindex_)
      - PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keyframe_)>(
          reinterpret_cast<char*>(&_impl_.keyframe_),
          reinterpret_cast<char*>(&other->_impl_.keyframe_));
}

std::string FrameBucketEntry_proto::GetTypeName() const {
  return "FrameBucketEntry_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::FrameBucketEntry_proto*
Arena::CreateMaybeMessage< ::FrameBucketEntry_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::FrameBucketEntry_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
