// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HierarchyData.proto

#include "HierarchyData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR HierarchyData_proto::HierarchyData_proto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.podata_)*/{}
  , /*decltype(_impl_._podata_cached_byte_size_)*/{0}
  , /*decltype(_impl_.numnodes_)*/0u
  , /*decltype(_impl_.maxdepth_)*/0u} {}
struct HierarchyData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HierarchyData_protoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HierarchyData_protoDefaultTypeInternal() {}
  union {
    HierarchyData_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HierarchyData_protoDefaultTypeInternal _HierarchyData_proto_default_instance_;

// ===================================================================

class HierarchyData_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<HierarchyData_proto>()._impl_._has_bits_);
  static void set_has_numnodes(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_maxdepth(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

HierarchyData_proto::HierarchyData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HierarchyData_proto)
}
HierarchyData_proto::HierarchyData_proto(const HierarchyData_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  HierarchyData_proto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.podata_){from._impl_.podata_}
    , /*decltype(_impl_._podata_cached_byte_size_)*/{0}
    , decltype(_impl_.numnodes_){}
    , decltype(_impl_.maxdepth_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&_impl_.numnodes_, &from._impl_.numnodes_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.maxdepth_) -
    reinterpret_cast<char*>(&_impl_.numnodes_)) + sizeof(_impl_.maxdepth_));
  // @@protoc_insertion_point(copy_constructor:HierarchyData_proto)
}

inline void HierarchyData_proto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.podata_){arena}
    , /*decltype(_impl_._podata_cached_byte_size_)*/{0}
    , decltype(_impl_.numnodes_){0u}
    , decltype(_impl_.maxdepth_){0u}
  };
}

HierarchyData_proto::~HierarchyData_proto() {
  // @@protoc_insertion_point(destructor:HierarchyData_proto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HierarchyData_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.podata_.~RepeatedField();
}

void HierarchyData_proto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HierarchyData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:HierarchyData_proto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.podata_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.numnodes_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.maxdepth_) -
        reinterpret_cast<char*>(&_impl_.numnodes_)) + sizeof(_impl_.maxdepth_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* HierarchyData_proto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 numNodes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_numnodes(&has_bits);
          _impl_.numnodes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 maxDepth = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_maxdepth(&has_bits);
          _impl_.maxdepth_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 poData = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_podata(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 24) {
          _internal_add_podata(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HierarchyData_proto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HierarchyData_proto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 numNodes = 1;
  if (_internal_has_numnodes()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_numnodes(), target);
  }

  // optional uint32 maxDepth = 2;
  if (_internal_has_maxdepth()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_maxdepth(), target);
  }

  // repeated uint32 poData = 3;
  {
    int byte_size = _impl_._podata_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          3, _internal_podata(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HierarchyData_proto)
  return target;
}

size_t HierarchyData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HierarchyData_proto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 poData = 3;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.podata_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._podata_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional uint32 numNodes = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_numnodes());
    }

    // optional uint32 maxDepth = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_maxdepth());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HierarchyData_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const HierarchyData_proto*>(
      &from));
}

void HierarchyData_proto::MergeFrom(const HierarchyData_proto& from) {
  HierarchyData_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:HierarchyData_proto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.podata_.MergeFrom(from._impl_.podata_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.numnodes_ = from._impl_.numnodes_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.maxdepth_ = from._impl_.maxdepth_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void HierarchyData_proto::CopyFrom(const HierarchyData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HierarchyData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HierarchyData_proto::IsInitialized() const {
  return true;
}

void HierarchyData_proto::InternalSwap(HierarchyData_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.podata_.InternalSwap(&other->_impl_.podata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.maxdepth_)
      + sizeof(HierarchyData_proto::_impl_.maxdepth_)
      - PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.numnodes_)>(
          reinterpret_cast<char*>(&_impl_.numnodes_),
          reinterpret_cast<char*>(&other->_impl_.numnodes_));
}

std::string HierarchyData_proto::GetTypeName() const {
  return "HierarchyData_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HierarchyData_proto*
Arena::CreateMaybeMessage< ::HierarchyData_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HierarchyData_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
