// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HierarchyData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HierarchyData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HierarchyData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HierarchyData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HierarchyData_2eproto {
  static const uint32_t offsets[];
};
class HierarchyData_proto;
struct HierarchyData_protoDefaultTypeInternal;
extern HierarchyData_protoDefaultTypeInternal _HierarchyData_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::HierarchyData_proto* Arena::CreateMaybeMessage<::HierarchyData_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class HierarchyData_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:HierarchyData_proto) */ {
 public:
  inline HierarchyData_proto() : HierarchyData_proto(nullptr) {}
  ~HierarchyData_proto() override;
  explicit PROTOBUF_CONSTEXPR HierarchyData_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HierarchyData_proto(const HierarchyData_proto& from);
  HierarchyData_proto(HierarchyData_proto&& from) noexcept
    : HierarchyData_proto() {
    *this = ::std::move(from);
  }

  inline HierarchyData_proto& operator=(const HierarchyData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HierarchyData_proto& operator=(HierarchyData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const HierarchyData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const HierarchyData_proto* internal_default_instance() {
    return reinterpret_cast<const HierarchyData_proto*>(
               &_HierarchyData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HierarchyData_proto& a, HierarchyData_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(HierarchyData_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HierarchyData_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HierarchyData_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HierarchyData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const HierarchyData_proto& from);
  void MergeFrom(const HierarchyData_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HierarchyData_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HierarchyData_proto";
  }
  protected:
  explicit HierarchyData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoDataFieldNumber = 3,
    kNumNodesFieldNumber = 1,
    kMaxDepthFieldNumber = 2,
  };
  // repeated uint32 poData = 3;
  int podata_size() const;
  private:
  int _internal_podata_size() const;
  public:
  void clear_podata();
  private:
  uint32_t _internal_podata(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_podata() const;
  void _internal_add_podata(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_podata();
  public:
  uint32_t podata(int index) const;
  void set_podata(int index, uint32_t value);
  void add_podata(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      podata() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_podata();

  // optional uint32 numNodes = 1;
  bool has_numnodes() const;
  private:
  bool _internal_has_numnodes() const;
  public:
  void clear_numnodes();
  uint32_t numnodes() const;
  void set_numnodes(uint32_t value);
  private:
  uint32_t _internal_numnodes() const;
  void _internal_set_numnodes(uint32_t value);
  public:

  // optional uint32 maxDepth = 2;
  bool has_maxdepth() const;
  private:
  bool _internal_has_maxdepth() const;
  public:
  void clear_maxdepth();
  uint32_t maxdepth() const;
  void set_maxdepth(uint32_t value);
  private:
  uint32_t _internal_maxdepth() const;
  void _internal_set_maxdepth(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HierarchyData_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > podata_;
    mutable std::atomic<int> _podata_cached_byte_size_;
    uint32_t numnodes_;
    uint32_t maxdepth_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HierarchyData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HierarchyData_proto

// optional uint32 numNodes = 1;
inline bool HierarchyData_proto::_internal_has_numnodes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool HierarchyData_proto::has_numnodes() const {
  return _internal_has_numnodes();
}
inline void HierarchyData_proto::clear_numnodes() {
  _impl_.numnodes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t HierarchyData_proto::_internal_numnodes() const {
  return _impl_.numnodes_;
}
inline uint32_t HierarchyData_proto::numnodes() const {
  // @@protoc_insertion_point(field_get:HierarchyData_proto.numNodes)
  return _internal_numnodes();
}
inline void HierarchyData_proto::_internal_set_numnodes(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.numnodes_ = value;
}
inline void HierarchyData_proto::set_numnodes(uint32_t value) {
  _internal_set_numnodes(value);
  // @@protoc_insertion_point(field_set:HierarchyData_proto.numNodes)
}

// optional uint32 maxDepth = 2;
inline bool HierarchyData_proto::_internal_has_maxdepth() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool HierarchyData_proto::has_maxdepth() const {
  return _internal_has_maxdepth();
}
inline void HierarchyData_proto::clear_maxdepth() {
  _impl_.maxdepth_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t HierarchyData_proto::_internal_maxdepth() const {
  return _impl_.maxdepth_;
}
inline uint32_t HierarchyData_proto::maxdepth() const {
  // @@protoc_insertion_point(field_get:HierarchyData_proto.maxDepth)
  return _internal_maxdepth();
}
inline void HierarchyData_proto::_internal_set_maxdepth(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.maxdepth_ = value;
}
inline void HierarchyData_proto::set_maxdepth(uint32_t value) {
  _internal_set_maxdepth(value);
  // @@protoc_insertion_point(field_set:HierarchyData_proto.maxDepth)
}

// repeated uint32 poData = 3;
inline int HierarchyData_proto::_internal_podata_size() const {
  return _impl_.podata_.size();
}
inline int HierarchyData_proto::podata_size() const {
  return _internal_podata_size();
}
inline void HierarchyData_proto::clear_podata() {
  _impl_.podata_.Clear();
}
inline uint32_t HierarchyData_proto::_internal_podata(int index) const {
  return _impl_.podata_.Get(index);
}
inline uint32_t HierarchyData_proto::podata(int index) const {
  // @@protoc_insertion_point(field_get:HierarchyData_proto.poData)
  return _internal_podata(index);
}
inline void HierarchyData_proto::set_podata(int index, uint32_t value) {
  _impl_.podata_.Set(index, value);
  // @@protoc_insertion_point(field_set:HierarchyData_proto.poData)
}
inline void HierarchyData_proto::_internal_add_podata(uint32_t value) {
  _impl_.podata_.Add(value);
}
inline void HierarchyData_proto::add_podata(uint32_t value) {
  _internal_add_podata(value);
  // @@protoc_insertion_point(field_add:HierarchyData_proto.poData)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
HierarchyData_proto::_internal_podata() const {
  return _impl_.podata_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
HierarchyData_proto::podata() const {
  // @@protoc_insertion_point(field_list:HierarchyData_proto.poData)
  return _internal_podata();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
HierarchyData_proto::_internal_mutable_podata() {
  return &_impl_.podata_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
HierarchyData_proto::mutable_podata() {
  // @@protoc_insertion_point(field_mutable_list:HierarchyData_proto.poData)
  return _internal_mutable_podata();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HierarchyData_2eproto
