// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InvBindData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_InvBindData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_InvBindData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_InvBindData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_InvBindData_2eproto {
  static const uint32_t offsets[];
};
class InvBindData_proto;
struct InvBindData_protoDefaultTypeInternal;
extern InvBindData_protoDefaultTypeInternal _InvBindData_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::InvBindData_proto* Arena::CreateMaybeMessage<::InvBindData_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class InvBindData_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:InvBindData_proto) */ {
 public:
  inline InvBindData_proto() : InvBindData_proto(nullptr) {}
  ~InvBindData_proto() override;
  explicit PROTOBUF_CONSTEXPR InvBindData_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InvBindData_proto(const InvBindData_proto& from);
  InvBindData_proto(InvBindData_proto&& from) noexcept
    : InvBindData_proto() {
    *this = ::std::move(from);
  }

  inline InvBindData_proto& operator=(const InvBindData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline InvBindData_proto& operator=(InvBindData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const InvBindData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const InvBindData_proto* internal_default_instance() {
    return reinterpret_cast<const InvBindData_proto*>(
               &_InvBindData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InvBindData_proto& a, InvBindData_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(InvBindData_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InvBindData_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InvBindData_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InvBindData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const InvBindData_proto& from);
  void MergeFrom(const InvBindData_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(InvBindData_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "InvBindData_proto";
  }
  protected:
  explicit InvBindData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoDataFieldNumber = 2,
    kNumMatFieldNumber = 1,
  };
  // repeated float poData = 2;
  int podata_size() const;
  private:
  int _internal_podata_size() const;
  public:
  void clear_podata();
  private:
  float _internal_podata(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_podata() const;
  void _internal_add_podata(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_podata();
  public:
  float podata(int index) const;
  void set_podata(int index, float value);
  void add_podata(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      podata() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_podata();

  // optional uint32 numMat = 1;
  bool has_nummat() const;
  private:
  bool _internal_has_nummat() const;
  public:
  void clear_nummat();
  uint32_t nummat() const;
  void set_nummat(uint32_t value);
  private:
  uint32_t _internal_nummat() const;
  void _internal_set_nummat(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:InvBindData_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > podata_;
    uint32_t nummat_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_InvBindData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InvBindData_proto

// optional uint32 numMat = 1;
inline bool InvBindData_proto::_internal_has_nummat() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool InvBindData_proto::has_nummat() const {
  return _internal_has_nummat();
}
inline void InvBindData_proto::clear_nummat() {
  _impl_.nummat_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t InvBindData_proto::_internal_nummat() const {
  return _impl_.nummat_;
}
inline uint32_t InvBindData_proto::nummat() const {
  // @@protoc_insertion_point(field_get:InvBindData_proto.numMat)
  return _internal_nummat();
}
inline void InvBindData_proto::_internal_set_nummat(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.nummat_ = value;
}
inline void InvBindData_proto::set_nummat(uint32_t value) {
  _internal_set_nummat(value);
  // @@protoc_insertion_point(field_set:InvBindData_proto.numMat)
}

// repeated float poData = 2;
inline int InvBindData_proto::_internal_podata_size() const {
  return _impl_.podata_.size();
}
inline int InvBindData_proto::podata_size() const {
  return _internal_podata_size();
}
inline void InvBindData_proto::clear_podata() {
  _impl_.podata_.Clear();
}
inline float InvBindData_proto::_internal_podata(int index) const {
  return _impl_.podata_.Get(index);
}
inline float InvBindData_proto::podata(int index) const {
  // @@protoc_insertion_point(field_get:InvBindData_proto.poData)
  return _internal_podata(index);
}
inline void InvBindData_proto::set_podata(int index, float value) {
  _impl_.podata_.Set(index, value);
  // @@protoc_insertion_point(field_set:InvBindData_proto.poData)
}
inline void InvBindData_proto::_internal_add_podata(float value) {
  _impl_.podata_.Add(value);
}
inline void InvBindData_proto::add_podata(float value) {
  _internal_add_podata(value);
  // @@protoc_insertion_point(field_add:InvBindData_proto.poData)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
InvBindData_proto::_internal_podata() const {
  return _impl_.podata_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
InvBindData_proto::podata() const {
  // @@protoc_insertion_point(field_list:InvBindData_proto.poData)
  return _internal_podata();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
InvBindData_proto::_internal_mutable_podata() {
  return &_impl_.podata_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
InvBindData_proto::mutable_podata() {
  // @@protoc_insertion_point(field_mutable_list:InvBindData_proto.poData)
  return _internal_mutable_podata();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_InvBindData_2eproto
