// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JointData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_JointData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_JointData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_JointData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_JointData_2eproto {
  static const uint32_t offsets[];
};
class JointData_proto;
struct JointData_protoDefaultTypeInternal;
extern JointData_protoDefaultTypeInternal _JointData_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::JointData_proto* Arena::CreateMaybeMessage<::JointData_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class JointData_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:JointData_proto) */ {
 public:
  inline JointData_proto() : JointData_proto(nullptr) {}
  ~JointData_proto() override;
  explicit PROTOBUF_CONSTEXPR JointData_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JointData_proto(const JointData_proto& from);
  JointData_proto(JointData_proto&& from) noexcept
    : JointData_proto() {
    *this = ::std::move(from);
  }

  inline JointData_proto& operator=(const JointData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointData_proto& operator=(JointData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const JointData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const JointData_proto* internal_default_instance() {
    return reinterpret_cast<const JointData_proto*>(
               &_JointData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JointData_proto& a, JointData_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(JointData_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointData_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointData_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JointData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const JointData_proto& from);
  void MergeFrom(const JointData_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JointData_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "JointData_proto";
  }
  protected:
  explicit JointData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoDataFieldNumber = 2,
    kNumJointsFieldNumber = 1,
  };
  // repeated uint32 poData = 2;
  int podata_size() const;
  private:
  int _internal_podata_size() const;
  public:
  void clear_podata();
  private:
  uint32_t _internal_podata(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_podata() const;
  void _internal_add_podata(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_podata();
  public:
  uint32_t podata(int index) const;
  void set_podata(int index, uint32_t value);
  void add_podata(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      podata() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_podata();

  // optional uint32 numJoints = 1;
  bool has_numjoints() const;
  private:
  bool _internal_has_numjoints() const;
  public:
  void clear_numjoints();
  uint32_t numjoints() const;
  void set_numjoints(uint32_t value);
  private:
  uint32_t _internal_numjoints() const;
  void _internal_set_numjoints(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:JointData_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > podata_;
    mutable std::atomic<int> _podata_cached_byte_size_;
    uint32_t numjoints_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_JointData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JointData_proto

// optional uint32 numJoints = 1;
inline bool JointData_proto::_internal_has_numjoints() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool JointData_proto::has_numjoints() const {
  return _internal_has_numjoints();
}
inline void JointData_proto::clear_numjoints() {
  _impl_.numjoints_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t JointData_proto::_internal_numjoints() const {
  return _impl_.numjoints_;
}
inline uint32_t JointData_proto::numjoints() const {
  // @@protoc_insertion_point(field_get:JointData_proto.numJoints)
  return _internal_numjoints();
}
inline void JointData_proto::_internal_set_numjoints(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.numjoints_ = value;
}
inline void JointData_proto::set_numjoints(uint32_t value) {
  _internal_set_numjoints(value);
  // @@protoc_insertion_point(field_set:JointData_proto.numJoints)
}

// repeated uint32 poData = 2;
inline int JointData_proto::_internal_podata_size() const {
  return _impl_.podata_.size();
}
inline int JointData_proto::podata_size() const {
  return _internal_podata_size();
}
inline void JointData_proto::clear_podata() {
  _impl_.podata_.Clear();
}
inline uint32_t JointData_proto::_internal_podata(int index) const {
  return _impl_.podata_.Get(index);
}
inline uint32_t JointData_proto::podata(int index) const {
  // @@protoc_insertion_point(field_get:JointData_proto.poData)
  return _internal_podata(index);
}
inline void JointData_proto::set_podata(int index, uint32_t value) {
  _impl_.podata_.Set(index, value);
  // @@protoc_insertion_point(field_set:JointData_proto.poData)
}
inline void JointData_proto::_internal_add_podata(uint32_t value) {
  _impl_.podata_.Add(value);
}
inline void JointData_proto::add_podata(uint32_t value) {
  _internal_add_podata(value);
  // @@protoc_insertion_point(field_add:JointData_proto.poData)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
JointData_proto::_internal_podata() const {
  return _impl_.podata_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
JointData_proto::podata() const {
  // @@protoc_insertion_point(field_list:JointData_proto.poData)
  return _internal_podata();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
JointData_proto::_internal_mutable_podata() {
  return &_impl_.podata_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
JointData_proto::mutable_podata() {
  // @@protoc_insertion_point(field_mutable_list:JointData_proto.poData)
  return _internal_mutable_podata();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_JointData_2eproto
