// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SkelEntry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SkelEntry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SkelEntry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SkelEntry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SkelEntry_2eproto {
  static const uint32_t offsets[];
};
class SkelEntry_proto;
struct SkelEntry_protoDefaultTypeInternal;
extern SkelEntry_protoDefaultTypeInternal _SkelEntry_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SkelEntry_proto* Arena::CreateMaybeMessage<::SkelEntry_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class SkelEntry_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:SkelEntry_proto) */ {
 public:
  inline SkelEntry_proto() : SkelEntry_proto(nullptr) {}
  ~SkelEntry_proto() override;
  explicit PROTOBUF_CONSTEXPR SkelEntry_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SkelEntry_proto(const SkelEntry_proto& from);
  SkelEntry_proto(SkelEntry_proto&& from) noexcept
    : SkelEntry_proto() {
    *this = ::std::move(from);
  }

  inline SkelEntry_proto& operator=(const SkelEntry_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline SkelEntry_proto& operator=(SkelEntry_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const SkelEntry_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const SkelEntry_proto* internal_default_instance() {
    return reinterpret_cast<const SkelEntry_proto*>(
               &_SkelEntry_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SkelEntry_proto& a, SkelEntry_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(SkelEntry_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SkelEntry_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SkelEntry_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SkelEntry_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SkelEntry_proto& from);
  void MergeFrom(const SkelEntry_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SkelEntry_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SkelEntry_proto";
  }
  protected:
  explicit SkelEntry_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPNodeNameFieldNumber = 3,
    kNodeIndexFieldNumber = 1,
    kParentIndexFieldNumber = 2,
  };
  // optional bytes pNodeName = 3;
  bool has_pnodename() const;
  private:
  bool _internal_has_pnodename() const;
  public:
  void clear_pnodename();
  const std::string& pnodename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pnodename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pnodename();
  PROTOBUF_NODISCARD std::string* release_pnodename();
  void set_allocated_pnodename(std::string* pnodename);
  private:
  const std::string& _internal_pnodename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pnodename(const std::string& value);
  std::string* _internal_mutable_pnodename();
  public:

  // optional sint32 nodeIndex = 1;
  bool has_nodeindex() const;
  private:
  bool _internal_has_nodeindex() const;
  public:
  void clear_nodeindex();
  int32_t nodeindex() const;
  void set_nodeindex(int32_t value);
  private:
  int32_t _internal_nodeindex() const;
  void _internal_set_nodeindex(int32_t value);
  public:

  // optional sint32 parentIndex = 2;
  bool has_parentindex() const;
  private:
  bool _internal_has_parentindex() const;
  public:
  void clear_parentindex();
  int32_t parentindex() const;
  void set_parentindex(int32_t value);
  private:
  int32_t _internal_parentindex() const;
  void _internal_set_parentindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SkelEntry_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pnodename_;
    int32_t nodeindex_;
    int32_t parentindex_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SkelEntry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SkelEntry_proto

// optional sint32 nodeIndex = 1;
inline bool SkelEntry_proto::_internal_has_nodeindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SkelEntry_proto::has_nodeindex() const {
  return _internal_has_nodeindex();
}
inline void SkelEntry_proto::clear_nodeindex() {
  _impl_.nodeindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t SkelEntry_proto::_internal_nodeindex() const {
  return _impl_.nodeindex_;
}
inline int32_t SkelEntry_proto::nodeindex() const {
  // @@protoc_insertion_point(field_get:SkelEntry_proto.nodeIndex)
  return _internal_nodeindex();
}
inline void SkelEntry_proto::_internal_set_nodeindex(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.nodeindex_ = value;
}
inline void SkelEntry_proto::set_nodeindex(int32_t value) {
  _internal_set_nodeindex(value);
  // @@protoc_insertion_point(field_set:SkelEntry_proto.nodeIndex)
}

// optional sint32 parentIndex = 2;
inline bool SkelEntry_proto::_internal_has_parentindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SkelEntry_proto::has_parentindex() const {
  return _internal_has_parentindex();
}
inline void SkelEntry_proto::clear_parentindex() {
  _impl_.parentindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline int32_t SkelEntry_proto::_internal_parentindex() const {
  return _impl_.parentindex_;
}
inline int32_t SkelEntry_proto::parentindex() const {
  // @@protoc_insertion_point(field_get:SkelEntry_proto.parentIndex)
  return _internal_parentindex();
}
inline void SkelEntry_proto::_internal_set_parentindex(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.parentindex_ = value;
}
inline void SkelEntry_proto::set_parentindex(int32_t value) {
  _internal_set_parentindex(value);
  // @@protoc_insertion_point(field_set:SkelEntry_proto.parentIndex)
}

// optional bytes pNodeName = 3;
inline bool SkelEntry_proto::_internal_has_pnodename() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SkelEntry_proto::has_pnodename() const {
  return _internal_has_pnodename();
}
inline void SkelEntry_proto::clear_pnodename() {
  _impl_.pnodename_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SkelEntry_proto::pnodename() const {
  // @@protoc_insertion_point(field_get:SkelEntry_proto.pNodeName)
  return _internal_pnodename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SkelEntry_proto::set_pnodename(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.pnodename_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SkelEntry_proto.pNodeName)
}
inline std::string* SkelEntry_proto::mutable_pnodename() {
  std::string* _s = _internal_mutable_pnodename();
  // @@protoc_insertion_point(field_mutable:SkelEntry_proto.pNodeName)
  return _s;
}
inline const std::string& SkelEntry_proto::_internal_pnodename() const {
  return _impl_.pnodename_.Get();
}
inline void SkelEntry_proto::_internal_set_pnodename(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pnodename_.Set(value, GetArenaForAllocation());
}
inline std::string* SkelEntry_proto::_internal_mutable_pnodename() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pnodename_.Mutable(GetArenaForAllocation());
}
inline std::string* SkelEntry_proto::release_pnodename() {
  // @@protoc_insertion_point(field_release:SkelEntry_proto.pNodeName)
  if (!_internal_has_pnodename()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.pnodename_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pnodename_.IsDefault()) {
    _impl_.pnodename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void SkelEntry_proto::set_allocated_pnodename(std::string* pnodename) {
  if (pnodename != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pnodename_.SetAllocated(pnodename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pnodename_.IsDefault()) {
    _impl_.pnodename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SkelEntry_proto.pNodeName)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SkelEntry_2eproto
