// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SkelEntry.proto

#include "SkelEntry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR SkelEntry_proto::SkelEntry_proto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.pnodename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nodeindex_)*/0
  , /*decltype(_impl_.parentindex_)*/0} {}
struct SkelEntry_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SkelEntry_protoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SkelEntry_protoDefaultTypeInternal() {}
  union {
    SkelEntry_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SkelEntry_protoDefaultTypeInternal _SkelEntry_proto_default_instance_;

// ===================================================================

class SkelEntry_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<SkelEntry_proto>()._impl_._has_bits_);
  static void set_has_nodeindex(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_parentindex(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_pnodename(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

SkelEntry_proto::SkelEntry_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:SkelEntry_proto)
}
SkelEntry_proto::SkelEntry_proto(const SkelEntry_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  SkelEntry_proto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pnodename_){}
    , decltype(_impl_.nodeindex_){}
    , decltype(_impl_.parentindex_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.pnodename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pnodename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_pnodename()) {
    _this->_impl_.pnodename_.Set(from._internal_pnodename(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.nodeindex_, &from._impl_.nodeindex_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.parentindex_) -
    reinterpret_cast<char*>(&_impl_.nodeindex_)) + sizeof(_impl_.parentindex_));
  // @@protoc_insertion_point(copy_constructor:SkelEntry_proto)
}

inline void SkelEntry_proto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pnodename_){}
    , decltype(_impl_.nodeindex_){0}
    , decltype(_impl_.parentindex_){0}
  };
  _impl_.pnodename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pnodename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SkelEntry_proto::~SkelEntry_proto() {
  // @@protoc_insertion_point(destructor:SkelEntry_proto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SkelEntry_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pnodename_.Destroy();
}

void SkelEntry_proto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SkelEntry_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:SkelEntry_proto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.pnodename_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.nodeindex_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.parentindex_) -
        reinterpret_cast<char*>(&_impl_.nodeindex_)) + sizeof(_impl_.parentindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* SkelEntry_proto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional sint32 nodeIndex = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_nodeindex(&has_bits);
          _impl_.nodeindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional sint32 parentIndex = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_parentindex(&has_bits);
          _impl_.parentindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes pNodeName = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_pnodename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SkelEntry_proto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SkelEntry_proto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional sint32 nodeIndex = 1;
  if (_internal_has_nodeindex()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(1, this->_internal_nodeindex(), target);
  }

  // optional sint32 parentIndex = 2;
  if (_internal_has_parentindex()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(2, this->_internal_parentindex(), target);
  }

  // optional bytes pNodeName = 3;
  if (_internal_has_pnodename()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_pnodename(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SkelEntry_proto)
  return target;
}

size_t SkelEntry_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SkelEntry_proto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bytes pNodeName = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_pnodename());
    }

    // optional sint32 nodeIndex = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_nodeindex());
    }

    // optional sint32 parentIndex = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_parentindex());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SkelEntry_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const SkelEntry_proto*>(
      &from));
}

void SkelEntry_proto::MergeFrom(const SkelEntry_proto& from) {
  SkelEntry_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:SkelEntry_proto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_pnodename(from._internal_pnodename());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.nodeindex_ = from._impl_.nodeindex_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.parentindex_ = from._impl_.parentindex_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void SkelEntry_proto::CopyFrom(const SkelEntry_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SkelEntry_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SkelEntry_proto::IsInitialized() const {
  return true;
}

void SkelEntry_proto::InternalSwap(SkelEntry_proto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pnodename_, lhs_arena,
      &other->_impl_.pnodename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.parentindex_)
      + sizeof(SkelEntry_proto::_impl_.parentindex_)
      - PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.nodeindex_)>(
          reinterpret_cast<char*>(&_impl_.nodeindex_),
          reinterpret_cast<char*>(&other->_impl_.nodeindex_));
}

std::string SkelEntry_proto::GetTypeName() const {
  return "SkelEntry_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SkelEntry_proto*
Arena::CreateMaybeMessage< ::SkelEntry_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SkelEntry_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
