// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vec3Data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Vec3Data_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Vec3Data_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Vec3Data_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Vec3Data_2eproto {
  static const uint32_t offsets[];
};
class Vec3Data_proto;
struct Vec3Data_protoDefaultTypeInternal;
extern Vec3Data_protoDefaultTypeInternal _Vec3Data_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Vec3Data_proto* Arena::CreateMaybeMessage<::Vec3Data_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Vec3Data_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:Vec3Data_proto) */ {
 public:
  inline Vec3Data_proto() : Vec3Data_proto(nullptr) {}
  ~Vec3Data_proto() override;
  explicit PROTOBUF_CONSTEXPR Vec3Data_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec3Data_proto(const Vec3Data_proto& from);
  Vec3Data_proto(Vec3Data_proto&& from) noexcept
    : Vec3Data_proto() {
    *this = ::std::move(from);
  }

  inline Vec3Data_proto& operator=(const Vec3Data_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3Data_proto& operator=(Vec3Data_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Vec3Data_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec3Data_proto* internal_default_instance() {
    return reinterpret_cast<const Vec3Data_proto*>(
               &_Vec3Data_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vec3Data_proto& a, Vec3Data_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec3Data_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3Data_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec3Data_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vec3Data_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Vec3Data_proto& from);
  void MergeFrom(const Vec3Data_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Vec3Data_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Vec3Data_proto";
  }
  protected:
  explicit Vec3Data_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // optional float x = 1;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // optional float y = 2;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // optional float z = 3;
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Vec3Data_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    float x_;
    float y_;
    float z_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Vec3Data_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vec3Data_proto

// optional float x = 1;
inline bool Vec3Data_proto::_internal_has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Vec3Data_proto::has_x() const {
  return _internal_has_x();
}
inline void Vec3Data_proto::clear_x() {
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float Vec3Data_proto::_internal_x() const {
  return _impl_.x_;
}
inline float Vec3Data_proto::x() const {
  // @@protoc_insertion_point(field_get:Vec3Data_proto.x)
  return _internal_x();
}
inline void Vec3Data_proto::_internal_set_x(float value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.x_ = value;
}
inline void Vec3Data_proto::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Vec3Data_proto.x)
}

// optional float y = 2;
inline bool Vec3Data_proto::_internal_has_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Vec3Data_proto::has_y() const {
  return _internal_has_y();
}
inline void Vec3Data_proto::clear_y() {
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float Vec3Data_proto::_internal_y() const {
  return _impl_.y_;
}
inline float Vec3Data_proto::y() const {
  // @@protoc_insertion_point(field_get:Vec3Data_proto.y)
  return _internal_y();
}
inline void Vec3Data_proto::_internal_set_y(float value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.y_ = value;
}
inline void Vec3Data_proto::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Vec3Data_proto.y)
}

// optional float z = 3;
inline bool Vec3Data_proto::_internal_has_z() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Vec3Data_proto::has_z() const {
  return _internal_has_z();
}
inline void Vec3Data_proto::clear_z() {
  _impl_.z_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float Vec3Data_proto::_internal_z() const {
  return _impl_.z_;
}
inline float Vec3Data_proto::z() const {
  // @@protoc_insertion_point(field_get:Vec3Data_proto.z)
  return _internal_z();
}
inline void Vec3Data_proto::_internal_set_z(float value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.z_ = value;
}
inline void Vec3Data_proto::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Vec3Data_proto.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Vec3Data_2eproto
